### ISSUE TITLE
Uprawnienia głównej gałęzi

### ISSUE THREAD

**Issue by Paperocean** [hololense-project/gui#1]
Zezwolenie na tworzenie nowych branchy od głównej gałęzi ułatwiłoby strukturę projektu. Dzięki temu moglibyśmy od razu tworzyć własne branche i je forkować, zamiast robić to bezpośrednio z głównej gałęzi. @sumadvena

**Comment by sumadvena** [comment]
Jasne, dobrze że dajesz znać. Dzisiaj będzie

**Comment by sumadvena** [comment]
@Paperocean zmieniłem uprawnienia wszystkich z read na write
potwierdź prosze czy działa
